spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8082



resilience4j.circuitbreaker:
  instances:
    comments:
      slidingWindowSize: 8
      minimumOfCalls: 4