spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8090


resilience4j.circuitbreaker:
  instances:
    comments:
      slidingWindowSize: 4
      minimumNumberOfCalls: 2
      permittedNumberOfCallsInHalfOpenState: 2
      waiDurationInOpenState: 10000
      slowCallDurationThreshold: 2000
      slowCallRateThreshold: 50